language: python
python:
  # - "2.6"
  - "2.7"
services: mysql
env:
  # - DJANGO=1.2.7
  # - DJANGO=1.3.1
  #- DJANGO=1.4.3 DJANGO_SETTINGS_MODULE="zakladnik.travis_settings"
  - DJANGO=1.6.2
install:
  - pip install -q Django==$DJANGO
  - pip install django-debug-toolbar
  #- python setup.py -q install
before_script:
# - "pep8 --exclude=migrations --ignore=E501,E225 src"
# - pyflakes -x W src
  #- mysql -e 'create database mysite_db;'
  #- python manage.py syncdb --noinput
script:
  - python manage.py test
